version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: company
    ports:
      - 6789:6789

  app-server:
    container_name: server
    image: fiit-company_app-server:latest
    depends_on:
      - db
    links:
      - db
    ports:
      - "8080:8080"
